spring.datasource.url=jdbc:postgresql://postgresdb:5432/productsdb
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.batch.jdbc.initialize-schema=always
spring.jpa.hibernate.ddl-auto=create-drop
spring.batch.jdbc.table-prefix=BATCH_
spring.main.allow-bean-definition-overriding=true
spring.batch.job.enabled=false

management.tracing.sampling.probability=1

server.port=8081

management.endpoints.web.exposure.include=beans,env,health,info,metrics,mappings,prometheus
management.endpoint.health.show-details=always
management.health.probes.enabled=true

# logging.level.com.example.batchprocessing=DEBUG
# logging.level.org.springframework.web=DEBUG
# debug=true

logging.level.com.ivanfranchin.moviesapi=DEBUG